#!/usr/bin/env -iS /opt/pwn.college/bash

PATH=/usr/bin

CHALLENGE=$RANDOM$RANDOM$RANDOM$RANDOM$RANDOM
RESPONSE="$1"

# This disables command injection. If you can find a bypass of it, let Zardus know!
set -T
trap '[[ $BASH_SUBSHELL -gt 0 ]] && exit' DEBUG

if (( RESPONSE == CHALLENGE ))
then
	echo "Success!"
	cat /flag
else
	echo "Wrong!"
	#cat /flag | md5sum
fi
