#!/usr/bin/env -iS /opt/pwn.college/bash

# props to HyperCube for the idea for this challenge

PATH=/usr/bin
RESPONSE="$1"

# This disables command injection. If you can find a bypass of it, let Zardus know!
set -T
readonly BASH_SUBSHELL # props to HAL50000 for the bypass necessitating this fix
trap '[[ $BASH_SUBSHELL -gt 0 ]] && exit' DEBUG

if (( RESPONSE == RANDOM ))
then
	echo "Success!"
	cat /flag
else
	echo "Wrong!"
	rm /flag
fi
