#!/usr/bin/env -iS /opt/pwn.college/bash

# This neat trick was generously contributed by WilyWizard!

PATH=/usr/bin

WORKDIR=$(mktemp -d)
[ -n "$WORKDIR" ] || exit 1
cd $WORKDIR

doit() {
	echo -n ""
	read INPUT < <(head -n1 | tr -cd "[\-~]")
	eval "$INPUT"
}

doit
