#!/usr/bin/env -iS /opt/pwn.college/bash

PATH=/usr/bin

WORKDIR=$(mktemp -d)
[ -n "$WORKDIR" ] || exit 1
cp "$1" "$WORKDIR/dangerous-script.sh"
cd $WORKDIR

doit() {
	echo -n ""
	cat dangerous-script.sh | tr -cd "[\n $\-/0-9A-Za-z]" | grep -E "^(echo|read|sleep) " > safe-script.sh
	bash safe-script.sh
}

doit
